### ISSUE TITLE
HTTPS and dev mode

### ISSUE THREAD

**Issue by classikd** [greenpdx/vue3d#3]
Running the dev mode gives me an error page, i don't know why :
![err2](https://user-images.githubusercontent.com/5224312/32131487-62dcc812-bbaf-11e7-9bf2-942d4c1878c6.JPG)

There is no error displayed in the console.
Using non-secure protocol in dev-server.js file solved my problem (line 67)
`var uri = 'http://localhost:' + port`

// Chrome 62, Windows 10, Firewall & Antivirus disabled by the way

**Comment by greenpdx** [comment]
Yes you are correct.
fixed by ae68bfa7d85ae8bacfb493e47ab6ce3f22b37890
